skinparam dpi 150
skinparam monochrome true
skinparam style strictuml

skinparam activityBackgroundColor white
skinparam activityDiamondBackgroundColor white
skinparam actorBackgroundColor white
skinparam classAttributeIconSize 0
skinparam classBackgroundColor white
skinparam databaseBackgroundColor white
skinparam fileBackgroundColor white
skinparam participantBackgroundColor white

<style>
  jsonDiagram {
    BackGroundColor White
    LineThickness 1
    RoundCorner 0

    arrow {
      LineThickness 1
    }

    highlight {
      BackGroundColor LightGray
    }
  }

  wbsDiagram {
    BackgroundColor White
  }
</style>
